#ifndef OPENGRAPHDB_H
#define OPENGRAPHDB_H

#pragma once

/* Auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>

#define OGDB_INVALID_ID UINT64_MAX

struct OgdbHandle {
  uint8_t _private;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

const char *ogdb_last_error(void);

struct OgdbHandle *ogdb_init(const char *path);

struct OgdbHandle *ogdb_open(const char *path);

void ogdb_close(struct OgdbHandle *handle);

uint64_t ogdb_create_node(struct OgdbHandle *handle,
                          const char *labels_json,
                          const char *properties_json);

uint64_t ogdb_add_edge(struct OgdbHandle *handle,
                       uint64_t src,
                       uint64_t dst,
                       const char *edge_type,
                       const char *properties_json);

char *ogdb_query(struct OgdbHandle *handle, const char *cypher);

int32_t ogdb_import(struct OgdbHandle *handle, const char *format, const char *src_path);

int32_t ogdb_export(struct OgdbHandle *handle, const char *dst_path, const char *format);

int32_t ogdb_backup(struct OgdbHandle *handle, const char *dst_path);

int32_t ogdb_checkpoint(struct OgdbHandle *handle);

char *ogdb_metrics(struct OgdbHandle *handle);

void ogdb_free(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPENGRAPHDB_H */
