import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, CheckCircle2, XCircle } from 'lucide-react'
import type { ClaimsStatus } from '@/components/landing/ClaimsBadge'

type LoadState =
  | { kind: 'loading' }
  | { kind: 'ready'; data: ClaimsStatus }
  | { kind: 'error'; message: string }

function formatDate(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  return d.toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC')
}

function evidenceHref(evidence: string | undefined): string | null {
  if (!evidence) return null
  if (/^https?:\/\//.test(evidence)) return evidence
  const trimmed = evidence.replace(/^cd\s+frontend\s+&&\s+/, '')
  const match = trimmed.match(/e2e\/[\w./-]+\.spec\.ts/)
  const path = match ? match[0] : trimmed.startsWith('e2e/') ? trimmed : null
  if (!path) return null
  const normalized = path.endsWith('.spec.ts') ? path : `${path}.spec.ts`
  return `https://github.com/asheshgoplani/opengraphdb/blob/main/frontend/${normalized}`
}

export default function ClaimsPage() {
  const [state, setState] = useState<LoadState>({ kind: 'loading' })

  useEffect(() => {
    fetch('/claims-status.json', { cache: 'no-store' })
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        return res.json() as Promise<ClaimsStatus>
      })
      .then((data) => setState({ kind: 'ready', data }))
      .catch((err) =>
        setState({ kind: 'error', message: err instanceof Error ? err.message : String(err) }),
      )
  }, [])

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border/60 bg-card/50">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4 sm:px-6">
          <Link
            to="/"
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" aria-hidden="true" />
            Back to landing
          </Link>
          <a
            href="https://github.com/asheshgoplani/opengraphdb"
            target="_blank"
            rel="noreferrer noopener"
            className="text-sm text-muted-foreground hover:text-foreground"
          >
            GitHub
          </a>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6">
        <h1 className="font-display text-4xl font-light tracking-tight sm:text-5xl">
          Claim verification
        </h1>
        <p className="mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground">
          Every claim OpenGraphDB makes on its landing page is backed by a real end-to-end test.
          This page lists each claim, the spec that proves it, the last time the spec ran, and
          whether it is currently green. Generated by{' '}
          <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-[0.82em]">
            scripts/verify-claims.sh
          </code>
          .
        </p>

        {state.kind === 'loading' && (
          <div className="mt-10 rounded-lg border border-border/70 bg-card/60 p-6 text-sm text-muted-foreground">
            Loading claim status…
          </div>
        )}

        {state.kind === 'error' && (
          <div
            data-testid="claims-page-error"
            role="alert"
            className="mt-10 rounded-lg border border-destructive/50 bg-destructive/15 p-6 text-sm text-destructive dark:text-destructive"
          >
            Could not load <code>/claims-status.json</code>: {state.message}. Run{' '}
            <code className="rounded bg-muted px-1 font-mono">scripts/verify-claims.sh</code> to
            generate it.
          </div>
        )}

        {state.kind === 'ready' && (
          <>
            <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-3">
              <div className="rounded-lg border border-border/70 bg-card/60 p-4">
                <p className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
                  Build
                </p>
                <p className="mt-1 font-mono text-lg">{state.data.sha}</p>
              </div>
              <div className="rounded-lg border border-border/70 bg-card/60 p-4">
                <p className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
                  Last verified
                </p>
                <p className="mt-1 text-sm">{formatDate(state.data.date)}</p>
              </div>
              <div className="rounded-lg border border-border/70 bg-card/60 p-4">
                <p className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
                  Status
                </p>
                <p className="mt-1 text-sm" data-testid="claims-page-summary">
                  {(() => {
                    const reds = state.data.entries.filter((e) => e.status === 'red').length
                    const greens = state.data.entries.filter((e) => e.status === 'green').length
                    return reds === 0
                      ? `All ${greens} claims green`
                      : `${reds} red · ${greens} green`
                  })()}
                </p>
              </div>
            </div>

            <div className="mt-8 overflow-hidden rounded-lg border border-border/70">
              <table
                data-testid="claims-table"
                className="w-full border-collapse text-left text-sm"
              >
                <thead className="bg-muted/60 text-xs uppercase tracking-[0.12em] text-muted-foreground">
                  <tr>
                    <th className="px-4 py-3 font-medium">Status</th>
                    <th className="px-4 py-3 font-medium">Claim</th>
                    <th className="px-4 py-3 font-medium">Test</th>
                    <th className="px-4 py-3 font-medium">Last run</th>
                  </tr>
                </thead>
                <tbody>
                  {state.data.entries.map((entry) => {
                    const href = evidenceHref(entry.evidence)
                    return (
                      <tr
                        key={entry.id}
                        data-testid={`claims-row-${entry.id}`}
                        data-status={entry.status}
                        className="border-t border-border/50 align-top"
                      >
                        <td className="px-4 py-4">
                          {entry.status === 'green' ? (
                            <span className="inline-flex items-center gap-1 text-accent dark:text-accent">
                              <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
                              green
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1 text-destructive dark:text-destructive">
                              <XCircle className="h-4 w-4" aria-hidden="true" />
                              red
                            </span>
                          )}
                        </td>
                        <td className="px-4 py-4">
                          <p className="font-mono text-xs text-muted-foreground">{entry.id}</p>
                          <p className="mt-1 leading-relaxed">{entry.claim}</p>
                        </td>
                        <td className="px-4 py-4 text-xs">
                          {entry.evidence && href ? (
                            <a
                              href={href}
                              target="_blank"
                              rel="noreferrer noopener"
                              className="font-mono text-foreground/80 underline decoration-dotted underline-offset-4 hover:text-foreground"
                            >
                              {entry.evidence}
                            </a>
                          ) : (
                            <span className="font-mono text-muted-foreground">
                              {entry.evidence ?? '—'}
                            </span>
                          )}
                        </td>
                        <td className="px-4 py-4 text-xs text-muted-foreground">
                          {formatDate(entry.last_run)}
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>

            <p className="mt-6 text-xs text-muted-foreground">
              Numbers we publish, not numbers we promise. CI re-runs{' '}
              <code className="rounded bg-muted px-1 py-0.5 font-mono">
                scripts/verify-claims.sh
              </code>{' '}
              on every push to <code>main</code>; a red entry here blocks the build.
            </p>
          </>
        )}
      </main>
    </div>
  )
}
