#!/usr/bin/env bash
# EVAL-RUST-QUALITY-CYCLE3 H7 regression gate.
#
# ogdb-node and ogdb-python both carry feature-gated
# `#![cfg_attr(feature = "<feat>", allow(unsafe_op_in_unsafe_fn))]` at
# crate root. The narrowing only holds because today neither crate
# contains a hand-written `unsafe { ... }` block or `unsafe fn`. If a
# future PR adds one, the workspace lint should catch it — but the
# feature-gated allow on the macro path makes the lint silent. This
# gate fires the alarm: any hand-written unsafe in the binding crates
# fails CI and forces the maintainer to either (a) move that code to a
# scoped sub-module with its own justification, or (b) revert to a
# crate-wide allow with explicit acknowledgement.
set -euo pipefail

ROOT="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
fail=0

for crate in ogdb-node ogdb-python; do
  src="$ROOT/crates/$crate/src"
  [[ -d "$src" ]] || { echo "FAIL: $src missing" >&2; exit 1; }
  # Match `unsafe {` or `unsafe fn` outside the comment context. We
  # tolerate `// ... unsafe ...` lines and `unsafe extern "C"` only when
  # generated by macros (those don't appear in source).
  hits=$(grep -RnE '(^|[^/])unsafe[[:space:]]*(\{|fn[[:space:]])' "$src" || true)
  if [[ -n "$hits" ]]; then
    echo "FAIL: $crate has hand-written unsafe — feature-gated allow no longer safe (H7):" >&2
    echo "$hits" >&2
    fail=1
  else
    echo "ok: $crate has no hand-written unsafe (H7)"
  fi
done

exit "$fail"
