#!/usr/bin/env bash
# C6-H1 / C6-H2 regression gate: every runnable Rust block in
# user-facing markdown (README.md / SPEC.md / DESIGN.md / ARCHITECTURE.md
# / documentation/*.md) must compile against the shipped ogdb-core
# surface.
#
# Why a dedicated gate (vs. extending check-design-vs-impl.sh):
#   The cycles 4+5 design-vs-impl gate is a fast grep that catches
#   *named-method* drift (`use opengraphdb::`, `params!`, `db.importer()`,
#   `query_df`, etc.). It is structurally blind to *signature* drift
#   (wrong arg count, wrong return type, missing `From` impl) — which is
#   exactly the shape of both cycle-6 HIGHs:
#     - C6-H1: README.md:36 called `db.create_node(&[..], &..)` but
#       `Database::create_node` takes 0 args (the labels+props variant
#       is `create_node_with`). Copy-paste yielded E0061.
#     - C6-H2: DESIGN.md §24 returned `Result<(), DbError>` and called
#       `db.query(...)?`, but `Database::query` returns
#       `Result<_, QueryError>` and `From<QueryError> for DbError` is
#       not implemented. Copy-paste yielded E0277.
#
# Methodology lesson: grep ≠ compile. The C5 audit declared the C4-H3
# fix CLOSED based on grep alone; C6 caught the regression only because
# the audit added a `cargo check` sweep. This script bakes that sweep
# into CI so the next signature drift fails at PR time, not at the next
# manual audit.
#
# Heuristic for "runnable" vs "design sketch":
#   We only compile-check ```rust blocks whose first non-blank,
#   non-comment line starts with `use ogdb_core::`. That is the
#   established "this is a copy-pasteable embedding example" signal —
#   matches README.md:32 and DESIGN.md:1584 today, skips the ~20
#   trait-definition / future-API / CLI-impl sketches throughout
#   DESIGN.md that legitimately don't compile.
#
# Future widening: drop the `use ogdb_core::` heuristic and add an
# explicit `<!-- doc-compile: skip -->` opt-out marker for sketches.
# The current shape is conservative on purpose — every false positive
# would block unrelated PRs and erode trust in the gate.
set -euo pipefail

# Skip when cargo / python3 are unavailable (e.g. docs-only PR runner
# without the rust toolchain). The rust CI lane runs scripts/test.sh
# which sources cargo, so the gate runs there.
if ! command -v cargo >/dev/null 2>&1 || ! command -v python3 >/dev/null 2>&1; then
  echo "[check-doc-rust-blocks] cargo or python3 unavailable; skipping (CI rust lane runs this gate)." >&2
  exit 0
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

DOCS=(README.md ARCHITECTURE.md SPEC.md DESIGN.md)
for f in documentation/*.md; do
  [[ -e "$f" ]] && DOCS+=("$f")
done

EXISTING=()
for p in "${DOCS[@]}"; do
  [[ -f "$p" ]] && EXISTING+=("$p")
done
if [[ ${#EXISTING[@]} -eq 0 ]]; then
  exit 0
fi

# Scratch crate under target/ so cargo's incremental cache is reused
# across runs (first run is slow, subsequent runs sub-second).
SCRATCH_DIR="$REPO_ROOT/target/check-doc-rust-blocks"
mkdir -p "$SCRATCH_DIR/src"

cat > "$SCRATCH_DIR/Cargo.toml" <<'TOML_EOF'
# Generated by scripts/check-doc-rust-blocks.sh — do not edit by hand.
# Re-generated each run. Compile-checks fenced rust blocks extracted
# from user-facing markdown (C6-H1 / C6-H2 regression gate).
[package]
name = "ogdb-doc-rust-blocks-check"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ogdb-core = { path = "__REPO_ROOT__/crates/ogdb-core" }

[workspace]
TOML_EOF
sed -i "s|__REPO_ROOT__|$REPO_ROOT|g" "$SCRATCH_DIR/Cargo.toml"

EXTRACT_REPORT=$(python3 - "$SCRATCH_DIR/src/lib.rs" "${EXISTING[@]}" <<'PY'
import re, sys

out_path = sys.argv[1]
docs = sys.argv[2:]

block_re = re.compile(r'^```rust\b.*?$\n(.*?)^```$', re.DOTALL | re.MULTILINE)

out = ['#![allow(unused, dead_code, clippy::all)]\n']
extracted = []

for doc in docs:
    try:
        text = open(doc).read()
    except OSError:
        continue
    for m in block_re.finditer(text):
        body = m.group(1)
        first = next((l.strip() for l in body.splitlines()
                      if l.strip() and not l.strip().startswith('//')), '')
        # Only compile-check explicit embedding samples.
        if not first.startswith('use ogdb_core::'):
            continue
        line = text[:m.start()].count("\n") + 1
        anchor = re.sub(r'[^a-zA-Z0-9]', '_', doc).lower() + f'_l{line}'

        # If the block defines its own `fn`, drop it into a module
        # verbatim. Otherwise wrap the statement-level body in a
        # `?`-friendly function so `db.query(..)?` etc. typecheck.
        has_fn = bool(re.search(r'^\s*fn\s+\w+', body, re.MULTILINE))
        if has_fn:
            out.append(f'\nmod _doc_{anchor} {{\n{body}\n}}\n')
        else:
            indented = '\n'.join('    ' + ln for ln in body.splitlines())
            out.append(
                f'\n#[allow(unreachable_code, unused_variables, unused_mut)]\n'
                f'fn _doc_{anchor}() -> Result<(), Box<dyn std::error::Error>> {{\n'
                f'{indented}\n'
                f'    Ok(())\n}}\n'
            )
        extracted.append(f'{doc}:{line}')

open(out_path, 'w').write('\n'.join(out))
print('\n'.join(extracted))
PY
)

if [[ -z "$EXTRACT_REPORT" ]]; then
  echo "[check-doc-rust-blocks] no \`use ogdb_core::\`-led runnable blocks found." >&2
  exit 0
fi

echo "[check-doc-rust-blocks] compile-checking extracted runnable blocks:" >&2
echo "$EXTRACT_REPORT" | sed 's/^/  - /' >&2

# Use a private CARGO_TARGET_DIR under target/ so the workspace's main
# target/ is not polluted with a non-workspace package's artifacts.
export CARGO_TARGET_DIR="$SCRATCH_DIR/_target"

if ! (cd "$SCRATCH_DIR" && cargo check --quiet 2>&1); then
  echo "" >&2
  echo "ERROR (C6-H1/H2): one or more 'use ogdb_core::'-led rust blocks in" >&2
  echo "user-facing docs do NOT compile against the shipped ogdb-core surface." >&2
  echo "" >&2
  echo "Affected blocks (line numbers above) were extracted to:" >&2
  echo "  $SCRATCH_DIR/src/lib.rs" >&2
  echo "" >&2
  echo "Reproduce locally:" >&2
  echo "  cd $SCRATCH_DIR && cargo check" >&2
  echo "" >&2
  echo "Common shapes this gate catches that the grep gates in" >&2
  echo "scripts/check-design-vs-impl.sh miss:" >&2
  echo "  - wrong arg count on a real method (E0061)" >&2
  echo "  - missing 'From<X> for Y' for the '?' operator (E0277)" >&2
  echo "  - signature drift after a method rename" >&2
  exit 1
fi

echo "[check-doc-rust-blocks] OK — all extracted runnable blocks compile." >&2
exit 0
